// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StitchLens.Data;

#nullable disable

namespace StitchLens.Data.Migrations
{
    [DbContext(typeof(StitchLensDbContext))]
    [Migration("20251021204651_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("StitchLens.Data.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HeightInches")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxColors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeshCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaletteJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessedImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("StitchType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WidthInches")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("YarnBrandId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("YarnBrandId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("StitchLens.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StitchLens.Data.Models.YarnBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("YarnBrands");
                });

            modelBuilder.Entity("StitchLens.Data.Models.YarnColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<double>("Lab_A")
                        .HasColumnType("REAL");

                    b.Property<double>("Lab_B")
                        .HasColumnType("REAL");

                    b.Property<double>("Lab_L")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("YardsPerSkein")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YarnBrandId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("YarnBrandId");

                    b.ToTable("YarnColors");
                });

            modelBuilder.Entity("StitchLens.Data.Models.Project", b =>
                {
                    b.HasOne("StitchLens.Data.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StitchLens.Data.Models.YarnBrand", "YarnBrand")
                        .WithMany()
                        .HasForeignKey("YarnBrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");

                    b.Navigation("YarnBrand");
                });

            modelBuilder.Entity("StitchLens.Data.Models.YarnColor", b =>
                {
                    b.HasOne("StitchLens.Data.Models.YarnBrand", "YarnBrand")
                        .WithMany("Colors")
                        .HasForeignKey("YarnBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YarnBrand");
                });

            modelBuilder.Entity("StitchLens.Data.Models.User", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("StitchLens.Data.Models.YarnBrand", b =>
                {
                    b.Navigation("Colors");
                });
#pragma warning restore 612, 618
        }
    }
}
